CREATE DATABASE IF NOT EXISTS COP4331;
USE COP4331;

DROP TABLE IF EXISTS Contacts;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Login VARCHAR(50) NOT NULL,
  Password VARCHAR(255) NOT NULL
);

CREATE TABLE Contacts (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(50),
  LastName VARCHAR(50),
  Phone VARCHAR(50),
  Email VARCHAR(50),
  UserID INT,
  FOREIGN KEY (UserID) REFERENCES Users(ID)
);

